### ISSUE TITLE
debugSwitch changed in newest foam-extend-3.1. Needs updating in RBFInterpolation

### ISSUE THREAD

**Issue by thijsgillebaart** [davidsblom/FOAM-FSI#55]
Debugswitch is no longer an int, but a debugSwitch object. This should be updated since it does not compile anymore with newest version of nextRelease brand of foam-extend-3.1.

**Comment by davidsblom** [comment]
Commit message: 
Update debug switch for the RBFInterpolation class after updates of foam-extend 3.1 nextRelease branch. The debugSwitch is changed to a debugSwitch object. However, this update causes problems when the system/controlDict file is used to modify the RBFInterpolation::debug variable since the variable is loaded in case a standard application of foam-extend is used, for example blockMesh.

**Comment by davidsblom** [comment]
The trick is to set the value of the debug switch in the run script:

``` bash
fsiFoam -DebugSwitches RBFInterpolation=1
```
